### PR TITLE
Use cloud_RoleName to identify apps for alerting

### PR DESCRIPTION
**Pull request by rkondratowicz**
https://tools.hmcts.net/jira/browse/BPS-933

### CODE REVIEW

**Comment by lgonczar** [comment]
Why did you base the query on role name, not role instance? It's a human-friendly name that can be accidentally changed.

**Comment by nitinprabhu** [comment]
> Why did you base the query on role name, not role instance? It's a human-friendly name that can be accidentally changed.

Since we use Spring Boot with the Application Insights Spring Boot starter it will use `spring.application.name` unless that changes we won't have impact ?

**Comment by lgonczar** [comment]
There is an invisible dependency now. I think we should either change it to the service name or at least make a note next to `spring.application.name` that alerts rely on it.

**Comment by nitinprabhu** [comment]
> There is an invisible dependency now. I think we should either change it to the service name (role instance) or at least make a note next to `spring.application.name` that alerts rely on it.

Agreed role instance would be nice

**Pull request merged**
