### PR TITLE
Introduce perftest environment

### PR DESCRIPTION
**Pull request by doncem**
### JIRA link (if applicable) ###

[Build bulk scan shared infra](https://tools.hmcts.net/jira/browse/BPS-1029)

### Change description ###

[This build](https://build.platform.hmcts.net/job/HMCTS_BSP/job/bulk-scan-shared-infrastructure/job/perftest/23/) finished all necessary components to proceed further. Error is same as for master so needs a separate investigation to address the issue

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by rkondratowicz** [comment]
can this be closed?

**Comment by doncem** [comment]
hm, single file left with modifications. @nitinprabhu what you think?

**Comment by nitinprabhu** [comment]
> hm, single file left with modifications. @nitinprabhu what you think?

Temporarily let's close it I need to reopen other too which needs to be merged so will also take care of this one

**Comment by doncem** [comment]
OK

**Pull request closed without merging**
