### PR TITLE
Move managed identity object ID for sandbox to the right file

### PR DESCRIPTION
**Pull request by lgonczar**
### Change description ###

Move managed identity object ID for sandbox to the right file

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by rkondratowicz** [comment]
can this be merged?
@lgonczar

**Comment by lgonczar** [comment]
> can this be merged?
> @lgonczar

@nitinprabhu?

**Comment by nitinprabhu** [comment]
> > can this be merged?
> > @lgonczar
> 
> @nitinprabhu?

We can merge it but there is some problem with state file which will replace notification queue connection string values in key vault. So once this is merged then you will need to update vault secrets for notification queue in AAT.

**Comment by lgonczar** [comment]
Best to keep the PR for now, I think.

**Pull request merged**
