### PR TITLE
Create publiclaw container

### PR DESCRIPTION
**Pull request by mdayican**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/BPS-1045

### Change description ###

Create publiclaw container

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by rkondratowicz** [comment]
can this be closed?

**Comment by mdayican** [comment]
> can this be closed?

I think no, we need to merge even containers are already created.

**Comment by nitinprabhu** [comment]
> > can this be closed?
> 
> I think no, we need to merge even containers are already created.

yes we need this else state file won't have the change

**Comment by mdayican** [comment]
we can not merge this for now. I am closing we will create new one when we can merge.

**Comment by nitinprabhu** [comment]
Temporarily closing below PRs we will fix them and reopen them when we start working on it.

**Comment by rkondratowicz** [comment]
can this be merged / closed?

**Comment by mdayican** [comment]
we need this pr but closing for now

**Pull request merged**
